### ISSUE TITLE
Website Todo

### ISSUE THREAD

**Issue by gvegayon** [USCbiostats/LAsBEST#1]
- [ ] Add actions/cache to avoid reinstalling
- [ ] Add instructions on how to update
- [ ] Create a new team like USCbiostats/LAsBEST2021 (which will include students)
- [ ] Update GH actions to use Make instead of Rscript
